name: tests

on: [push, pull_request]

jobs:
  test_ui:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ui
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm install
      - run: npm run-script lint
      - run: npm run-script test
      - run: npm install -g parcel-bundler
      - run: parcel build src/index.html
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - python: 3.8
            toxenv: flake8
            os: ubuntu-latest
          - python: 3.8
            toxenv: mypy
            os: ubuntu-latest
          - python: 3.8
            toxenv: pylint
            os: ubuntu-latest
          - python: 3.8
            toxenv: black
            os: ubuntu-latest
          - python: 3.7
            toxenv: py37
            os: ubuntu-latest
          - python: 3.7
            toxenv: py37
            os: ubuntu-latest
          - python: 3.8
            toxenv: py38
            os: ubuntu-latest
          - python: 3.9
            toxenv: py39
            os: ubuntu-latest
          - python: 3.8
            toxenv: py38
            os: macos-latest
          - python: 3.8
            toxenv: py38
            os: windows-latest

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{  matrix.python }}
      - name: install dependencies
        run: python -m pip install --upgrade pip tox
      - name: run
        env:
          TOXENV: ${{ matrix.toxenv }}
        run: tox
      - name: setup
        run: python setup.py install
